### ISSUE TITLE
issue with gnome 3.24

### ISSUE THREAD

**Issue by jgauth** [51v4n/i3-gnome#12]
I cannot get i3-gnome to work on gnome 3.24. 
i3 and gnome work fine on their own. When select i3-gnome with gdm and log in, i3 loads then the screen goes black except for the files I have on my gnome desktop. When I type, a small typing box appears in the bottom left of the screen but nothing appears to happen when I type any command.

The only way I can tell to exit/logoff is to turn off the computer. I'm not sure how to get logs screenshots because I can't actually do anything once I log in to i3-gnome

**Comment by 51v4n** [comment]
Hi,
All the issues regarding with this version (3.24) take place on `gnome-settings-daemon` [1] [2] 
Specificly you are struggling with [2], so, my suggestion is to upgrade to GNOME 3.26.x as seen here [3] otherwise, you'll not be able to use `i3-gnome`

[1] https://github.com/GNOME/gnome-settings-daemon/blob/master/NEWS
[2] https://bugs.archlinux.org/task/53800
[3] https://github.com/51v4n/i3-gnome/issues/9
