### ISSUE TITLE
Screenshots

### ISSUE THREAD

**Issue by wviana** [51v4n/i3-gnome#13]
You could place at least two screenshots to get more interest in this awesome project.

**Comment by antenore** [comment]
I agree it's an amazing project. But @wviana you can also submit a PR with a screenshot (^_-)

**Comment by 51v4n** [comment]
Thanks folks!, but there are no big visual changes to show up, with i3-gnome simply uses the native GNOME's tools to manage for example the GTK theme(s) and so on, instead of having a different tool to make the things work. That's why we didn't add screenshots.

It would be nice (if you wish) to share your screenshot, just to show how it looks working. My setup it's very simple, almost like default.
Let me know if you want to share your screenshot, for sure it would be on the README.

Thanks for the suggestion.
Cheers!
