### ISSUE TITLE
What all does using gnome as the desktop manager provide?

### ISSUE THREAD

**Issue by NullVoxPopuli** [51v4n/i3-gnome#21]
Maybe this is something that should go in the readme?

I think I had some mis-aligned expectations settings this up.

For example:
I expected that I'd be able to auto-switch monitors when I plugged an external one in to my laptop (full gnome provides this out of the box). 

(I still have my xrandr script bound to F2, so I'm not blocked by anything)

**Comment by 51v4n** [comment]
`i3-gnome` grabs some components that make a simple session work with the i3-wm (window manager) instead of `mutter` (the window manager of GNOME), by components i mean like sound, GTK theme customization, power manager, GNOME settings daemon (XSettings), you don't have any graphical component of GNOME's shell like extension, 

With `i3-gnome` in simplest words we're using GNOME as backend.
